### ISSUE TITLE
Discovered 3 lines that were not logged

### ISSUE THREAD

**Issue by dharmaturtle** [MemeLabs/overrustlelogs#5] opened 2016-02-03 13:00 UTC
I randomly found 3 lines that weren't logged here: http://dgg.overrustlelogs.net/Destinygg%20chatlog/February%202016/2016-02-03.txt

http://i.imgur.com/qBKDpIr.png

The problem was also in the webclient (obviously, my IRC echobot doesn't send text that doesn't exist) but then everyone started talking to me and I forgot to screenshot :|

Minor issue, but perhaps indicative of other issues?

**Comment by slugalisk** [comment] 2016-02-09 00:00
Nice catch! Maybe we can diff the scw and geemu logs to confirm a this issue was caused by a problem with orl logger. If it loses lines periodically chances are there will be inconsistencies.

Because the web client also missed these lines it may have been the chat server but it will take more investigation to be sure...

**Comment by dharmaturtle** [comment] 2016-02-09 00:30
Sorry, bad wording on my part. The problem was NOT displayed in webchat, meaning that it also showed the text in IRC. IRC and webchat displayed the same info.

The problem is probably not with the chat server.

**Comment by slugalisk** [comment] 2016-03-20 06:08
Without some sort of redundancy it's likely that we'll miss lines occasionally.  Fortunately this seems to be very uncommon. To verify this I downloaded the February chat logs for Destiny.gg chat from both servers currently running overrustlelogs logger, merged, and compared them

```
$ diff dgg/clean.txt scw/clean.txt
$ wc dgg/clean.txt 
 1791886 10904987 77312305 dgg/clean.txt
$ wc scw/clean.txt 
 1791886 10904987 77312305 scw/clean.txt
```

Either the code is reasonably stable or we have some sort of deterministic bug where lines are dropped silently. I strongly suspect this was some sort of transient error so I'm going to close this unless someone can provide evidence that it's a more serious problem.

**Closed as completed** 2016-03-20 06:08 UTC
